import React from 'react'
import _Form from '@/components/form/form'
import Head from "next/head";


export default function Contact() {

  return (
<div style={{"padding":"10px" ,"display":"grid"}}>

<Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



<_Form/>
 </div>
   
)
  }


  // .App {
  //   font-family: Arial, sans-serif;
  //   display: flex;
  //   flex-direction: column;
  //   align-items: center;
  //   margin-top: 50px;
  // }
  
  // form {
  //   width: 300px;
  //   border: 1px solid #ccc;
  //   padding: 20px;
  //   border-radius: 5px;
  //   box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.1);
  // }
  
  // label {
  //   display: block;
  //   margin-bottom: 5px;
  // }
  
  // input[type='radio'] {
  //   margin-right: 5px;
  // }
  
  // .error {
  //   color: red;
  //   font-size: 12px;
  //   margin-top: 5px;
  // }
  
  // input[type='email'],
  // textarea {
  //   width: 100%;
  //   padding: 8px;
  //   margin-bottom: 10px;
  //   border: 1px solid #ccc;
  //   border-radius: 5px;
  // }
  
  // button[type='submit'] {
  //   background-color: #007bff;
  //   color: white;
  //   border: none;
  //   padding: 10px 15px;
  //   border-radius: 5px;
  //   cursor: pointer;
  //   transition: background-color 0.3s ease;
  // }
  
  // button[type='submit']:hover {
  //   background-color: #0056b3;
  // }
  