import React from 'react'

import Head from "next/head";
export default function ForTattoostudios() {
  return (
    <div>


            <Head>
        <title>ForTattoostudios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        <h1>ForTattoostudios</h1>
      
    </div>
  )
}
