import React from 'react'
import _Form from '@/components/artistForm/form'
import Head from "next/head";


export default function JoinArtist() {
  return (
    <div>
             <Head>
        <title>JoinArtist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <h2> Join as an artist</h2>

      <_Form/>
    </div>
  )
}
