import React from 'react'
import Head from "next/head";

export default function page() {
  return (
    <div>
          <Head>
        <title>Style Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>Style guide</h1>
    </div>
  )
}
