import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import SearchField from "@/components/searchField";
import { useDispatch, useSelector } from "react-redux";
import { debounce } from "lodash";
import { fetchMultiData } from "@/action/action";
import { Parameters, tabs } from "@/components/parameters/params";
import { useRouter } from 'next/router'


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter()


  const [state, setState] = useState({
    value: "",
    key: "all",
  });


  const handleChange = debounce((event) => {
    setState((prevState) => ({
      ...prevState,
      value: event,
    }));
  }, 100);

  // useEffect(() => {
  //   const fetchData = async () => {
  //     try {
  //       const requestData = {
  //         ...Parameters,
  //         search_key:state.value

  //       };
  //       let responseData;
  //       responseData = await fetchMultiData(requestData);
  //       setState((prevState) => ({
  //         ...prevState,
  //         hints: responseData.data,
  //       }));
  //     } catch (error) {
  //       // Handle errors here
  //       console.error("Error fetching data:", error);
  //     }
  //   };

  //   fetchData();
  // }, [state.value]);

  const handleSubmits = () => {
    // setState((prevState) => ({
    //   ...prevState,
    //    value: state.value,
    //   // searchKey:event
    // }));
  };

  // useEffect(() => {
  //   fetchMultiData({...Parameters});
  // }, [state.value]);

  const onclick = (e) => {
    setState((prevState) => ({
      ...prevState,
      value: e,
    }));

router.push(`/search?term=${e}&category=${"all"}`)


  };

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        
        <SearchField

  isHome={"all"}



        /> 

              {/* <SearchField handleChange={handleChange}  hints={state.hints}   onclicks={onclicks} handleSubmits={handleSubmits}  value={state.value} /> */}


        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            width: "20%",
            "margin-top": "30px",
          }}
        >
          <Link href={`/search?term=${""}&category=${"tattoo"}`}>Tattoo</Link>
          <Link href={`/search?term=${""}&category=${"artist"}`}>Artist</Link>
          <Link href={`/search?term=${""}&category=${"flash"}`}>Flash</Link>
        </div>
      </main>
    </>
  );
}
