import React, { useState, useEffect, Suspense, useRef } from "react";

import Head from "next/head";
import { useRouter } from 'next/router'

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { InckState } from "@/context/Context";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { state ,dispatch} = InckState();
  const [count, setCount] = useState(0);
  console.log(count,";ldml;smc;lsdcm")


  // function test(e) {
  //   console.log(e ,"d;,cs;dc,'s")

  //   dispatch({
  //     type: "ADD_TO_CART",
  //     payload: e,
  //   })
  //  router.push(`/search?term=${''}&category=${e}`)

  //     }
 


  const handleButtonClick = () => {
    setCount(count + 1);
  };
  

  return (


  

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>

        

        {/* <button        onClick={() =>
                     
                    }   >  Tattoo</button> */}

 
<div style={{"display":"flex" ,"justifyContent":"space-between"}}>



         <Link href={`/search?term=${''}&category=${'all'}`}>All</Link>
    <Link href={`/search?term=${''}&category=${'tattoo'}`}>Tattoo</Link>


    <Link href={`/search?term=${''}&category=${'artist'}`}>Artist</Link>

    <Link href={`/search?term=${''}&category=${'flash'}`}>Flash</Link>



    </div>



    <p>Count: {count}</p>
      <button onClick={handleButtonClick}>Click me</button>



      </main>
    </>
  );
}


