import React from 'react'
import { Tab, Tabs, TabList, TabPanel } from 'react-tabs';
import 'react-tabs/style/react-tabs.css';

import Head from "next/head";


export default function klarna() {
  return (
    <div>
     
     <Head>
        <title>klarna</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



    <h1>Klarna</h1>


    </div>
  )
}
