import React from 'react'

import Head from "next/head";
// async function getData() {
//  axios('https://64d8b3d05f9bf5b879ce79aa.mockapi.io/products',{

//  }).then((e)=>{


// console.log(e,"succews")

//   })
//   .catch((e)=>console.log(e,"dcp[kls"))
 
// }
 



export default   function Dictionary() {
  // const data = await getData()

  return (
    <div>
           <Head>
        <title>Dictionary</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <h1>Dictionary</h1>
    </div>
  )
}

