import React from 'react'
import Head from "next/head";

export default function FAQ() {
  return (
    <div>
                <Head>
        <title>FAQ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Faq</h1>
    </div>
  )
}
